/**
 * tokens.json -> three platforms.
 *
 * Run with `bun run tokens` from the repo root. The outputs are written
 * straight into the app that consumes them and are committed: regenerating
 * them must be a reviewable diff, not a build-time surprise.
 *
 * Android needs two files because Findroid is not all Compose. The Kotlin
 * object feeds the Material 3 colour schemes; the XML resources feed
 * core/res/values/themes.xml and the View-based ExoPlayer control layouts,
 * which resolve ?attr/colorPrimary rather than reading a Compose value. :core
 * is the destination because both :app:phone and :app:tv depend on it.
 *
 * Shared/Cinema on the iOS side is inside an Xcode file-system synchronized
 * group, so a file written there joins the target with no project edit.
 */
import tokens from './tokens.json'

const ROOT = new URL('../../', import.meta.url).pathname

const CSS_OUT = `${ROOT}apps/web/src/styles/tokens.css`
const SWIFT_OUT = `${ROOT}apps/ios/Swiftfin/Shared/Cinema/CinemaTokens.swift`
const KOTLIN_OUT =
  `${ROOT}apps/android/findroid/core/src/main/java/it/davideghiotto/cinema/design/CinemaTokens.kt`
const ANDROID_XML_OUT = `${ROOT}apps/android/findroid/core/src/main/res/values/cinema_tokens.xml`

const NOTE = [
  'Generated by packages/design-tokens/build.ts -- do not edit.',
  `Source of truth: packages/design-tokens/tokens.json (${tokens.$name}).`,
]
const slashBanner = `${NOTE.map((line) => `// ${line}`).join('\n')}\n`
const blockBanner = `/*\n${NOTE.map((line) => `  ${line}`).join('\n')}\n*/\n`
// XML forbids `--` inside a comment, and the shared note contains one.
const xmlBanner = `<!--\n${NOTE.map((line) => `  ${line.replace('--', '-')}`).join('\n')}\n-->\n`

/**
 * kebab-case -> camelCase, for the Swift/Kotlin identifiers. Neither language
 * allows an identifier to start with a digit, so a scale step like "2xl" is
 * spelled out rather than silently emitted as code that will not compile.
 */
const IDENTIFIER_ALIASES: Record<string, string> = { '2xl': 'xxl', '3xl': 'xxxl' }
const camel = (key: string) =>
  (IDENTIFIER_ALIASES[key] ?? key).replace(/-(\w)/g, (_, c: string) => c.toUpperCase())

// --- web ---------------------------------------------------------------
function css() {
  const lines: string[] = []
  for (const [key, token] of Object.entries(tokens.color))
    lines.push(`  --${key}: ${token.hex};${token.use ? ` /* ${token.use} */` : ''}`)
  for (const [key, token] of Object.entries(tokens.alpha)) lines.push(`  --${key}: ${token.value};`)
  // Prefixed so they never collide with Tailwind's own --radius-*/--shadow-*/
  // --font-* theme namespaces; src/index.css bridges them into @theme.
  for (const [key, value] of Object.entries(tokens.radius)) lines.push(`  --rad-${key}: ${value};`)
  for (const [key, value] of Object.entries(tokens.shadow)) lines.push(`  --shad-${key}: ${value};`)
  for (const [key, value] of Object.entries(tokens.type)) lines.push(`  --type-${key}: ${value};`)
  lines.push(`  --ease: ${tokens.motion.ease};`)
  lines.push(`  --duration-fast: ${tokens.motion.fast};`)
  lines.push(`  --duration-base: ${tokens.motion.base};`)
  return `${blockBanner}\n:root {\n${lines.join('\n')}\n}\n`
}

// --- iOS ---------------------------------------------------------------
function swift() {
  const colors = Object.entries(tokens.color)
    .map(([key, token]) => `    static let ${camel(key)} = ${swiftColor(token.hex)} // ${token.hex}`)
    .join('\n')
  const radii = Object.entries(tokens.radius)
    .filter(([key]) => key !== 'pill')
    .map(([key, value]) => `    static let ${camel(key)}: CGFloat = ${remToPoints(value)}`)
    .join('\n')
  return `${slashBanner}
import SwiftUI

public enum CinemaTokens {
  public enum Palette {
${colors}
  }

  public enum Radius {
${radii}
    static let pill: CGFloat = 999
  }
}
`
}

/**
 * Colour components rather than a hex string: Swiftfin already defines its own
 * `Color.init(hex:)`, and a second one in this file would not compile. Literals
 * also cost nothing at runtime.
 */
function swiftColor(hex: string) {
  const [r, g, b] = channels(hex).map((c) => (c / 255).toFixed(4))
  return `Color(.sRGB, red: ${r}, green: ${g}, blue: ${b}, opacity: 1)`
}

function channels(hex: string) {
  const value = Number.parseInt(hex.slice(1), 16)
  return [(value >> 16) & 255, (value >> 8) & 255, value & 255]
}

// --- Android -----------------------------------------------------------
function kotlin() {
  const colors = Object.entries(tokens.color)
    .map(([key, token]) => `    val ${camel(key)} = Color(0xFF${token.hex.slice(1).toUpperCase()})`)
    .join('\n')
  const radii = Object.entries(tokens.radius)
    .filter(([key]) => key !== 'pill')
    .map(([key, value]) => `        val ${camel(key)} = ${remToPoints(value)}.dp`)
    .join('\n')
  return `${slashBanner}
package it.davideghiotto.cinema.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object CinemaTokens {
${colors}

    object Radius {
${radii}
        val pill = 999.dp
    }
}
`
}

/**
 * Findroid is not all Compose: `core/res/values/themes.xml` and the ExoPlayer
 * control layouts are Views resolving `?attr/colorPrimary` and `?attr/colorSurface`,
 * and the launcher and TV banner backgrounds are `@color` resources. Those need
 * the palette as Android resources, from the same source as everything else.
 */
function androidXml() {
  const colors = Object.entries(tokens.color)
    .map(([key, token]) => `    <color name="cinema_${key.replace(/-/g, '_')}">${token.hex}</color>`)
    .join('\n')
  return `<?xml version="1.0" encoding="utf-8"?>\n${xmlBanner}<resources>\n${colors}\n</resources>\n`
}

/** 1rem = 16 CSS px = 16 pt/dp. Mobile inherits the web's spacing rhythm. */
function remToPoints(value: string) {
  return Math.round(Number.parseFloat(value) * 16)
}

await Bun.write(CSS_OUT, css())
await Bun.write(SWIFT_OUT, swift())
await Bun.write(KOTLIN_OUT, kotlin())
await Bun.write(ANDROID_XML_OUT, androidXml())
console.log(`✓ ${tokens.$name} tokens -> web, ios, android`)
