#!/usr/bin/env bash
# Write the dashboard's .env, on the box, from the running containers.
#
#   ssh -t homelab 'bash ~/mediarr-dash/scripts/collect-env.sh'
#
# With NONINTERACTIVE=1 it asks nothing: the container keys are refreshed and
# every typed value is kept as it was. That is the right form for a re-run after
# rotating an *arr key, and the only form that works without a terminal.
#
# Every *arr keeps its API key inside its own config file, so the keys are read
# out of the containers directly and never travel anywhere. The two that cannot
# be read this way -- the Jellyfin token and the qBittorrent login -- are asked
# for. Re-running is safe: existing values are offered as the default, so a
# blank answer keeps what is already there.
set -euo pipefail

TARGET="${TARGET:-$HOME/mediarr-dash/.env}"
mkdir -p "$(dirname "$TARGET")"

# Load whatever is already there, so a re-run does not lose answers.
declare -A existing=()
if [[ -f "$TARGET" ]]; then
  while IFS='=' read -r key value; do
    [[ -n "$key" && "$key" != \#* ]] && existing["$key"]="$value"
  done < "$TARGET"
fi

note()  { printf '  %s\n' "$*" >&2; }
mask()  { local v="$1"; [[ -z "$v" ]] && echo "(empty)" || echo "${v:0:4}…${v: -2} (${#v} chars)"; }

from_container() { # name, command...
  local container="$1"; shift
  docker exec "$container" "$@" 2>/dev/null | tr -d '\r\n' || true
}

ask() { # varname, prompt, secret?
  local var="$1" prompt="$2" secret="${3:-}" current="${existing[$1]:-}" answer=""
  local suffix=""
  if [[ -n "${NONINTERACTIVE:-}" ]]; then printf '%s' "${!var:-$current}"; return; fi
  [[ -n "$current" ]] && suffix=" [keep $(mask "$current")]"
  if [[ -n "$secret" ]]; then
    read -r -s -p "  ${prompt}${suffix}: " answer </dev/tty; echo >&2
  else
    read -r -p "  ${prompt}${suffix}: " answer </dev/tty
  fi
  printf '%s' "${answer:-$current}"
}

echo "Reading API keys out of the containers…" >&2
RADARR_API_KEY=$(from_container radarr sed -n 's:.*<ApiKey>\(.*\)</ApiKey>.*:\1:p' /config/config.xml)
SONARR_API_KEY=$(from_container sonarr sed -n 's:.*<ApiKey>\(.*\)</ApiKey>.*:\1:p' /config/config.xml)
PROWLARR_API_KEY=$(from_container prowlarr sed -n 's:.*<ApiKey>\(.*\)</ApiKey>.*:\1:p' /config/config.xml)
# config.yaml holds six `apikey:` lines -- Bazarr's own plus one per provider
# and one each for Radarr and Sonarr. Only the one inside the `auth:` block is
# the key this dashboard needs, so the block is matched rather than the field.
BAZARR_API_KEY=$(from_container bazarr awk '
  /^auth:/       { inauth = 1; next }
  /^[a-z_]+:/    { inauth = 0 }
  inauth && $1 == "apikey:" { gsub(/["\047]/, "", $2); print $2; exit }
' /config/config/config.yaml)
JELLYSEERR_API_KEY=$(from_container jellyseerr node -p 'require("/app/config/settings.json").main.apiKey')

for pair in "radarr:$RADARR_API_KEY" "sonarr:$SONARR_API_KEY" "prowlarr:$PROWLARR_API_KEY" \
            "bazarr:$BAZARR_API_KEY" "jellyseerr:$JELLYSEERR_API_KEY"; do
  name="${pair%%:*}"; value="${pair#*:}"
  if [[ -n "$value" ]]; then note "$name  $(mask "$value")"; else note "$name  NOT FOUND — is the container running?"; fi
done

echo >&2
if [[ -z "${NONINTERACTIVE:-}" ]]; then
echo "The rest cannot be read from a container:" >&2
note "Jellyfin: Dashboard → API Keys → + , then paste it here."
note "qBittorrent: the Web UI login. Leave both blank if auth is bypassed for this subnet."
echo >&2
fi

JELLYFIN_API_KEY=$(ask JELLYFIN_API_KEY "Jellyfin API key" secret)
QBITTORRENT_USER=$(ask QBITTORRENT_USER "qBittorrent username")
QBITTORRENT_PASS=$(ask QBITTORRENT_PASS "qBittorrent password" secret)

echo >&2
DASHBOARD_PASSWORD=$(ask DASHBOARD_PASSWORD "Dashboard password (the one you will type to log in)" secret)
if [[ -z "$DASHBOARD_PASSWORD" ]]; then
  if [[ -n "${NONINTERACTIVE:-}" ]]; then
    # Nothing to keep and nobody to ask: mint one so the server can start, and
    # say where to read it. The next interactive run replaces it.
    DASHBOARD_PASSWORD=$(openssl rand -hex 12)
    note "no password was set — generated one, read it with: grep DASHBOARD_PASSWORD $TARGET"
  else
    echo "  A dashboard password is required — the server refuses to start without one." >&2
    exit 1
  fi
fi

# Keep the existing secret if there is one: rotating it logs every browser out.
SESSION_SECRET="${existing[SESSION_SECRET]:-$(openssl rand -hex 32)}"

umask 077
cat > "$TARGET" <<ENV
# Generated by scripts/collect-env.sh on $(date -Is). Not for git.
# Re-run that script to refresh; it keeps the values you typed.

DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
SESSION_SECRET=$SESSION_SECRET

JELLYSEERR_API_KEY=$JELLYSEERR_API_KEY
RADARR_API_KEY=$RADARR_API_KEY
SONARR_API_KEY=$SONARR_API_KEY
PROWLARR_API_KEY=$PROWLARR_API_KEY
BAZARR_API_KEY=$BAZARR_API_KEY
JELLYFIN_API_KEY=$JELLYFIN_API_KEY
QBITTORRENT_USER=$QBITTORRENT_USER
QBITTORRENT_PASS=$QBITTORRENT_PASS
ENV
chmod 600 "$TARGET"

echo >&2
echo "Wrote $TARGET (mode 600)." >&2
echo "Restart the stack to pick it up:  cd ~/mediarr-dash && docker compose up -d" >&2
